### ISSUE TITLE
Ability to Download Historic Prices into memory

### ISSUE THREAD

**Issue by Slashernator** [AnAlgoTrader/IG.Csharp.Api.Client#4]
Hi,
Not really an issue I suppose but I added this code to be able to read a set number of points into memory rather than file save.  I couldn't find the correct routine.  Thought I'd let you know if you wanted to implement it, also bad coding from my part too, soz.
        public HistoricalPricesResponse HistoricalData(string epic, string resolution, string record_limit) =>
            GetApiResponse<HistoricalPricesResponse>($"{PRICES_URI}/{epic}?resolution={resolution}&max={record_limit}", "3");

btw my own code had the resolution which is why it's a string but it parses, haven't got the code to work yet though.
Cheers,
Ad

**Comment by AnAlgoTrader** [comment]
Hi, the service to download data from IG delivers the response in pages, so the code has to control in which page we are. I have moved the logic from **_SaveHistoricalDataToFile_** to a separate method so you can use it and keep in memory if you wish.

The new method is GetHistoricalPrices. 

Be aware that there is a quota limit that IG applies to every account so if you exceed that number it will raise an error. The _**HistoricalPricesResponse**_ object contains metadata with the exact allowance in case you want to check it.

On the other hand, in order to use an enum from a string you can parse it with the Enum helper that is part of the c# language. 
I have left an example in the playground if you want to run it. It does parse a resolution from a string as an example.

https://github.com/AnAlgoTrader/IG.Csharp.Api.Client/blob/master/Playground/Program.cs
https://github.com/AnAlgoTrader/IG.Csharp.Api.Client/blob/master/Playground/DownloadDataExample.cs

**Comment by Slashernator** [comment]
Hi, Thanks again.
I've already written a couple of items to track the limit etc.
I'm using a windows form to control the program and subscribe etc. I'm having a bit of trouble integrating the listener but I should hopefully sort that soon.

**Comment by AnAlgoTrader** [comment]
You are bound to failure if you use Windows Forms. Try to move to WPF if you can. With WPF MVC you would  be able to set up a class that would use the listeners easily
